update ta4j version from 9to11
NitigyaS/Finapp pull request #1
Opened 2018-04-25 18:51 UTC by NikkiKumari

2018-04-25 19:01 UTC, NikkiKumari commented
Change class name StrategyAnalyser to BackTestAnalyser

2018-04-26 05:48 UTC, NitigyaS requested changes

2018-04-26 05:48 UTC, NitigyaS commented on src/main/java/Strategies/BackTestAnalyser.java
> -    private NumberOfTicksCriterion numTicks = new NumberOfTicksCriterion();
@NikkiKumari Can you also change the following variables name to numBar

2018-04-26 05:48 UTC, NitigyaS commented on src/main/java/Strategies/BackTestAnalyser.java
> -                    Tick entryTick = series.getTick(entry.getIndex());
Also change these to entryBar and other vars in the project.

2018-04-26 05:48 UTC, NitigyaS commented on src/main/java/Strategies/StrategyOne.java
> +import org.ta4j.core.indicators.*;
I do not think we need this line.

2018-04-26 05:48 UTC, NitigyaS commented on src/main/java/Strategies/StrategyOne.java
> +    RSIIndicator smrsi;
not required.

2018-05-04 12:21 UTC, merged